easy-ocw/install-osx.sh
easy-ocw/install-ubuntu.sh

- Change the structuring of the 'command' calls to check for installed
applications that are necessary for parts of the installation. This
should prevent false positives that lead to other errors later on.

CLIMATE-571 - Change Easy-OCW checks for installed applications

---

ocw-config-runner/example/simple_model_to_model_bias.yaml
ocw-config-runner/ocw_evaluation_from_config.py
ocw-config-runner/tests/test_config_runner.py

- Implements initial config based execution of evaluations. There are a number of missing features, the most obvious of which is the lack of support for all the available plot types in OCW. These and other things will be updated in tickets that follow.
- Included is a config for one of our example files (simple_model_to_model_bias). The evaluation area is   slightly changed, but other than that all is the same. It is assumed that the user has the files downloaded to /tmp when using this config file.

CLIMATE-575 - Initial config based evaluation runner implementation

---

ocw-config-runner/plot_generation.py

- Contour map plotting now properly handles a list of tuples of result
indices when plotting. Each tuple is plotted using all the other
configuration values by default.
- Contour map plot names now have an identifier number at the end that
corresponds with the result index used to generate them.

CLIMATE-602 - Add support for multiple contour map result indices

---

ocw/dataset_processor.py
ocw/tests/test_dataset_processor.py

Made the naming of the subregion optional at it is not a necessity, but a nice feature to keep track of datasets.

CLIMATE-597 - Subsetting a dataset should update the names attribute

---

ocw/plotter.py

- Update plotter.draw_contour_map docstring to specify proper expected
data shape.

CLIMATE-605 - Fix typo in plotter.draw_contour_map docstring

---

ocw-config-runner/tests/test_config_parsing.py

- A previous change split the various config parsing components out into
separate modules. The config parser import name was changed in the
test_config_parsing tests module but the actual call to the new import
was not.
- One of the logger mocks incorrectly referenced the old module name.
This was causing the mocking library to not recognize that the correct
logging function was in fact being called.

CLIMATE-607 - Fix broken config parser tests

---

.mailmap

- Updated this slightly since my local copy that I've had sitting around was a bit out of date. Hopefully I didn't overlook anyone or misspell something. It looks like everything is mapping back to apache names/emails properly when tested locally.
```
| -> git shortlog -sne
944  Michael Joyce <joyce@apache.org>
204  Cameron Eugene Goodale <goodale@apache.org>
57  Maziyar Boustani <boustani@apache.org>
52  Andrew Hart <ahart@apache.org>
39  Shakeh Elisabeth Khudikyan <skhudiky@apache.org>
34  Kim Whitehall <whitehall@apache.org>
22  Lewis John McGibbney <lewismc@apache.org>
16  jwhittel <jwhittel@unknown>
15  Huikyo Lee <huikyole@apache.org>
14  Ross Laidlaw <rlaidlaw@apache.org>
11  Alex Goodman <goodman@apache.org>
11  Paul Michael Ramirez <pramirez@apache.org>
7  Chris Mattmann …
```

CLIMATE-608 - Add mailmap file to repo

---

ocw/data_source/dap.py
ocw/data_source/esgf.py
ocw/data_source/local.py
ocw/data_source/rcmed.py
ocw/tests/test_dap.py
ocw/tests/test_local.py
ocw/tests/test_rcmed.py

- Add a 'source' flag to dataset origin information when loaded from a
data_source. This is set to 'local', 'dap', 'esgf', or 'rcmed'
depending on the data_source used.
- Update data_source tests to take new source flag into account.

CLIMATE-609 - Add data source flag to dataset origin information

---

easy-ocw/install-ubuntu.sh

Set the default ocw_path directory to the user's HOME directory so that running in quiet mode doesn't cause empty paths to be inserted into the user's RC file. This isn't foolproof but covers the VM build and the general use case that arises from reading the various guides on the Wiki.

CLIMATE-619 - Default ocw_path to user HOME dir

---

ocw-config-runner/configuration_parsing.py
ocw-config-runner/configuration_writer.py
ocw-config-runner/evaluation_creation.py
ocw-config-runner/tests/test_config_parsing.py
ocw-config-runner/tests/test_config_writer.py

Note, at the moment this does not include changes necessary to support subregions in the plot handling. That will be coming along shortly.

CLIMATE-639 - Add subregion support to config runner

---

ocw/utils.py

I have encountered with bunch of ESGF datasets that have time formats like %Y-%m-%dT%H:%M:%SZ, so I needed to add these two more formats in order to support them.

Needed to add two more possible time format for some ESGF datasets

---

ocw/data_source/esgf.py

by dropping "distrib=false" from URL the respond has the ESGF netCDF file that being download to user's local machine.

To get esgf netCDF file name should drop distrib=false

---

ocw/dataset_processor.py

- Fix: ocw.dataset_processor.ensemble now uses numpy.ma.mean instead of numpy.mean to properly handle missing values.

CLIMATE-650 - Fix the ensemble calculation

---

ocw/dataset_processor.py

In many cases, observational and model datasets have different units for the same variable. We need to update variable_unit_conversion module is needed in dataset_processor. This new module is based on water_flux_unit_conversion.

CLIMATE-643 - Updating unit conversion function 

---

ocw/dataset_processor.py

- Cleanup duplicate unit conversion code in dataset_processor that was
introduced in CLIMATE-643. water_flux_unit_conversion is no longer
duplicated unnecessarily in variable_unit_conversion.
- Factor out temperature_unit_conversion code from
variable_unit_conversion. Formatting and isolation now matches that of
water_flux_unit_conversion. These are both called from the
variable_unit_conversion function so there's a convenient wrapper for
this functionality (as was the functionality prior to this refactor).

CLIMATE-654 - Clean up duplicate unit conversion code

---

ocw/metrics.py
ocw/tests/test_metrics.py

- Remove metrics.SpatialMeanOfTemporalMeanBias 
- Add metrics.SpatialPatternTaylorDiagram
- Add functions calc_bias, calc_stddev, calc_stddev_ratio, calc_correlation, calc_rmse
- Update test_metrics.py

CLIMATE-657 - Adding functions to calculate metrics

---

ocw/metrics.py
ocw/tests/test_metrics.py

- delete: metrics.SpatialMeanOfTemporalMeanBias
- new examples will calculate this quantity in a more reasonable way

CLIMATE-659 - Remove SpatialMeanOfTemporalMeanBias

---

ocw/dataset.py

- ocw.dataset.spatial_boundaries uses np.min and np.max instead of min and max

CLIMATE-667 - OCW spatial_boundaries bug

---

ocw/dataset.py

- min and max functions in ocw.dataset.spatial_boundaries are replaced by numpy.min and numpy.max

CLIMATE-669 - OCW spatial_boundary bug

---

ocw/data_source/local.py

- ocw.data_source.local.load_multiple_files has been updated
- filename_patterns deleted
- common filename pattern can be added at the end of file_path
- the module output lists of OCW datasets and their names

CLIMATE-673 - Update the module to load multiple netcdf files

---

easy-ocw/conda-install.sh

- The conda-install.sh Easy-OCW script now sets PS1 prior to attempting
to source bashrc to ensure that conda is locatable after install.
- The post-miniconda bashrc source has been moved out the miniconda
install block.

CLIMATE-711 - Resolve bashrc sourcing issue in conda-install

---

ocw-vm/init-ocw-vm.sh

- Update the VM build script to use the new conda based dependency
install from Easy-OCW.
- Add activate of OCW conda environment to system .bashrc.
- Update script so "interactive mode" checks in the .bashrc file wont
break the build.

CLIMATE-712 - Update VM build to use conda install

---

ocw-ui/frontend/app/index.html

Updated index.html to use https rather than http when loading Google jsapi.
https://developers.google.com/loader/?hl=en
Fixes page not found / object not set when loading page.

CLIMATE-738 - Update  Google jsapi call to use https rather than http.

---

ocw/data_source/local.py

- In ocw.data_source.local.load_file, level_index is fixed as 1 (the 2nd dimension) if the input dataset has four dimensions.

CLIMATE-742 - ocw.data_source.local.py cannot properly detect the altitude dimension

---

ocw/data_source/rcmed.py

A reference to the RCMED Query Specification was already being used by the URL variable.
I was between adding the link to the "get_parameters_metadata()" method documentation or adding it to the Class documentation. I ended up going with the second option.
Let me know if you think this should go somewhere else and/or if the wording could be improved.

CLIMATE-691 - Add a link to the RCMED Query Specification.

---

ocw/utils.py

- the old longitude conversion is a correct way to handle datasets whose longitude values are between 180 and 360.

CLIMATE-743 - Partially restore utils.normalize_lat_lon_values

---

RCMES/cli_app.py

- This is a follow up of the previous ticket, CLIMATE-732. CLI now uses correct keys when calling dataset_processor.temporal_rebin.

CLIMATE-749 - Changing temporal_resolution key in CLI

---

RCMES/configuration_files/CORDEX-Africa_examples/Fig10a_cru.yaml
RCMES/configuration_files/CORDEX-Africa_examples/Fig4f_9bcd.yaml

- Unit of CRU's cloud fraction data in RCMED (dataset_id: 10, parameter_id:42) is %, whereas all of CORDEX Africa RCMs have dimensionless cloud fraction. 'multiplying_factor' option will match the unit between the observation and models.

CLIMATE-752 - Converting the unit of CRU cloud fraction by adding an option to configuration files

---

ocw/data_source/dap.py
ocw/tests/test_dap.py

This issue addresses https://issues.apache.org/jira/browse/CLIMATE-757
The previous file did not exist on the OpenDAP test server any longer. A new arbitrary file and variable are now selected instead.

CLIMATE-757 Fix ERROR: test suite for <class 'ocw.tests.test_dap.TestDap'>

---

ocw/data_source/dap.py
ocw/tests/test_dap.py

1.  Fix various Pylint complaints on dap.py and test_dap.py.
2.  Add extra logic to dap.py to inspect the dimensions list rather than just assuming time / lat / lon are the first three dimensions.
3.  Update the test cases to reflect the values found in the new test file added in CLIMATE-757.
4.  Update the name of the set up function in test_dap.py to ensure set up is called before executing tests.

CLIMATE-768 - Fix failing tests in test_dap.py.  Add extra logic to dap.py to check for named dimensions. 

---

ocw/tests/test_local.py

1.  Switched order of level and time to follow the convention of time / altitude / lat / lon so local.py would remove the correct altitude dimension.
2.  Corrected file variable handles from being overwritten.
3.  Updated the range for the lon values so they would not be normalized when read back from the file.
4. Pylint clean up.

CLIMATE-758 - Fix failing tests in test_local.py.

---

ocw/tests/test_dataset_processor.py

- fix tests in TestTemporalRebin class
`TemporalRebin()` function passes the received parameters to `_rcmes_calc_average_on_new_time_unit_K` which requires the unit to be `full`, `annual`, `monthly`, `daily`.

CLIMATE-759 - Fix failing test in test_dataset_processor.py

---

ocw/tests/test_dap.py
ocw/tests/test_dataset.py
ocw/tests/test_dataset_processor.py
ocw/tests/test_evaluation.py
ocw/tests/test_local.py
ocw/tests/test_metrics.py
ocw/tests/test_plotter.py
ocw/tests/test_rcmed.py
ocw/tests/test_utils.py

Following PEP8 violations are fixed
- Remove trailing whitespaces
- Fix lines with length > 79
- Add two blank lines after every function

CLIMATE-792 - Fix PEP8 violations in tests

---

ocw/data_source/local.py

This change will now show the filename string that gets passed into the function in the error message.

CLIMATE-817 - More informative error messages for data_source.load_file()

---

ocw/dataset_processor.py
ocw/tests/test_dataset_processor.py

This change allows for users to call ```write_netcdf()``` for datasets with 2D lat lon arrays. Waiting for @huikyole to test.

CLIMATE-821 - write_netcdf() assumes lat and lon are 1D arrays

---

conda_recipes/bottle/bld.bat
conda_recipes/bottle/build.sh
conda_recipes/bottle/meta.yaml
conda_recipes/esgf-pyclient/bld.bat
conda_recipes/esgf-pyclient/build.sh
conda_recipes/esgf-pyclient/meta.yaml
conda_recipes/myproxyclient/bld.bat
conda_recipes/myproxyclient/build.sh
conda_recipes/myproxyclient/meta.yaml
conda_recipes/ocw/bld.bat
conda_recipes/ocw/build.sh
conda_recipes/ocw/meta.yaml
conda_recipes/pydap/bld.bat
conda_recipes/pydap/build.sh
conda_recipes/pydap/meta.yaml
conda_recipes/sphinxcontrib-httpdomain/bld.bat
conda_recipes/sphinxcontrib-httpdomain/build.sh
conda_recipes/sphinxcontrib-httpdomain/meta.yaml

This commit includes conda package recipes for ocw as well as some specific dependencies which do not currently have packages on the main anaconda channel. Note that any attempt building the package from the recipe as is will install the most recently committed code, but this can be changed by setting `git_rev` to a specific release version in `ocw/meta.yaml`.

CLIMATE-829 - Add conda package recipes

---

ocw/tests/test_dap.py

- The tests fail because the dataset that I have used for testing does not contain time variable in it.
- The dap.py runs on a presumption that the dataset must contain the three variables time, lat and lon necessarily.

CLIMATE-830 Broken tests in dap.py

---

RCMES/configuration_files/ESGF_example/ESGF-Example.yaml
RCMES/run_RCMES.py
ocw/data_source/esgf.py
ocw/esgf/logon.py

The following bugs were fixed:
- Changed loader_name from 'ESGF' to 'esgf' in the config file to make it compatible with `DatasetLoader`.
- Changed the argument name of `variable` to `variable_name` in `esgf.py`, again for compatibility purposes with `DatasetLoader`.
- Added `bootstrap=True` when logging on via myproxyclient. If certificates were not found in the users ~/.esg/certificates directory, this would result in an SSLError since the directory would not exist on clean systems (eg a freshly installed VM in which the local ESGF examples were not ran).

CLIMATE-846 - ESGF loader fails with new changes to run_RCMES.py

---

ocw/tests/test_dap.py

- This PR comments the failing test case in test_dap.py as suggested by @lewismc.
- We can comment it out once we find a good fix. 
@jarifibrahim you are good to go with this now. Thanks.

CLIMATE-830 Reverting the broken test case in test_dap.py

---

ocw/dataset_processor.py

- dataset_processor.temporal_subset has been updated.

CLIMATE-860 - Fix dataset_processor.temporal_subset to remove the warning message

---

docs/source/data_source/data_sources.rst
easy-ocw/ocw-pip-dependencies.txt
examples/podaac_integration_example.py
ocw/data_source/podaac.py
ocw/data_source/podaac_datasource.py
ocw/dataset_loader.py
ocw/tests/test_podaac.py

- This PR adds PO.DAAC data source to ocw.
- This PR also addresses the required tests.
Any suggestions are welcome, Thanks.

Adding PO.DAAC data source along with the tests

---

conda_recipes/esgf-pyclient/bld.bat
conda_recipes/myproxyclient/bld.bat
conda_recipes/ocw/bld.bat
conda_recipes/podaacpy/bld.bat
conda_recipes/podaacpy/build.sh
conda_recipes/podaacpy/meta.yaml
conda_recipes/pydap/bld.bat
conda_recipes/sphinxcontrib-httpdomain/bld.bat

@lewismc @Omkar20895 Please let me know if coveralls is actually necessary for the `podaacpy` code to run. Since it is listed as a dependency in `setup.py`, I also had to build a conda recipe for it internally in order to get `podaacpy` to build which ended up being quite a pain to deal with. 
Anyway to test this, navigate to the `conda_recipes` directory, then run
```
conda update conda-build
conda build ocw
conda clean -pt
conda create -n test python
source activate test
conda install --use-local ocw
```

CLIMATE-862: More updates to conda recipe files

---

.travis.yml
ocw/data_source/local.py
test.sh

With this PR, the main python 3 incompatibility issue in `local.py` is fixed and we can now successfully finish the smoke tests on python 3. This will now let us see precisely which parts of the ocw codebase are not python 3 compatible with each of our CI builds.

CLIMATE-882 - local data source is not Python 3 compatible

---

ocw/plotter.py

The title is a slight misnomer, what's actually being done is making sure that plotting behavior is more consistent between user-installed matplotlib versions.

[CLIMATE-895] Make plotter compatible with matplotlib 2.0

---

RCMES/CORDEX/metadata_extractor.py

For now this is only being used for our soon to be shown CORDEX examples, but I do plan to make this a more permanent part of OCW with unit tests and documentation.
Example usage in an ipython shell:
```python
In [1]: from metadata_extractor import CORDEXMetadataExtractor, obs4MIPSMetadataExtractor
In [2]: obs_extractor = obs4MIPSMetadataExtractor('/proj3/data/obs4mips')
In [3]: models_extractor = CORDEXMetadataExtractor('/proj3/data/CORDEX/NAM-44/*')
In [4]: obs_extractor.instruments
Out[4]: 
{'AIRS',
'AMSRE',
'ATSR',
'AVISO',
'CALIOP',
'CERES-EBAF',
'GPCP-1DD',
'GPCP-SG',
'HIRS',
'MISR',
'MLS',
'MODIS',
'MODIS-Level',
'MODIS-level',
'OISST',
'QuikSCAT',
'RO',
'SSMI-MERIS',
'SSMI-NH',
'SSMI-SH',
'TES',
'TRMM-L3',
'ghgcci'}
In [5]: models_extractor.models
Out[5]: {'DMI-HIRHAM5', …
```

CLIMATE-926 - Metadata Extractors

---

ocw/dataset_processor.py

Needed this patch to get RCMES to work with CERES data and automatic temporal overlap.

CLIMATE-928 - temporal_subset should trim edges of dataset times to ensure months divide evenly into years

---

ocw/dataset_processor.py
ocw/utils.py

- Fixes a bug introduced by CLIMATE-928
- Minor fixes to CORDEX boundary generator to make it accept acronym inputs

CLIMATE-929 - Incorrect indices used for temporal subset after trimming

---

ocw/data_source/local.py
ocw/tests/test_local.py

This is mainly to ensure subsetting works properly with the obs4Mips files.

CLIMATE-930 - multiple file loader forces 2D lats and lons

---

ocw/plotter.py

CLIMATE-230 Line colors in time series cycles through too few colors
- Add option to time_series to specify color map.
- Add option to time_series to slice the color map by the number of plots to prevent using the same color more than once.

CLIMATE-230 Line colors in time series cycles through too few colors

---

ocw-ui/backend/rcmed_helpers.py
ocw-ui/frontend/app/scripts/controllers/rcmedselection.js
ocw-ui/frontend/test/spec/controllers/rcmedselection.js

CLIMATE-388 Make UI backend parameters endpoint more RESTful
- Change query parameter to path parameter.
- Change route annotation to get annotation.
- Pylint.

CLIMATE-388 Make UI backend parameters endpoint more RESTful

---

ocw-ui/backend/run_webservices.py

CLIMATE-762 Automate symlinking ocw-vm frontend to backend to allow for serving of files with bottle.
- Check if the symlink to the front end when the web services are started and create the link if it does not.

CLIMATE-762 Automate symlinking ocw-vm frontend to backend to allow for serving of files with bottle.

---

ocw-ui/frontend/app/scripts/controllers/parameterselect.js
ocw-ui/frontend/app/scripts/controllers/rcmedselection.js
ocw-ui/frontend/app/scripts/controllers/timeline.js
ocw-ui/frontend/app/scripts/controllers/worldmap.js
ocw-ui/frontend/app/views/main.html
ocw-ui/frontend/bower.json

CLIMATE-943 TypeError: Cannot set property uiDateValidator of undefined
- Upgraded to AngularJS 1.5 to fix error with date validator.
- Fixed issue in which date widget would not launch.
- Fixed issue in worldmap.js in which NaN lon / lat were processed which was throwing JavasScript error.
- Fixed issue in timeline.js in which undefined dates were process which was throwing JavasScript error.
- Fixed issue in which RCMED selection resets and throws JavaScript error.
- Removed explicit call to $scope.$apply(); which was throwing JavasScript error.
- Replace fa-remove with fa-times to restore missing dataset deletion icons.
- Changed copyright date to 2018.

CLIMATE-943 TypeError: Cannot set property uiDateValidator of undefined

---

ocw-ui/frontend/.jscsrc
ocw-ui/frontend/Gruntfile.js
ocw-ui/frontend/app/views/modelselect.html
ocw-ui/frontend/package.json

CLIMATE-945 Grunt Errors On Build Task
- Fix htmlmin parsing error on ocw-ui/frontend/app/views/modelselect.html.
- Added missing dependency for npmin.
- Add jscs dependency and rule file to replace deprecated functionality in jshint.

CLIMATE-945 Grunt Errors On Build Task

---

ocw/dataset.py

CLIMATE-353 Bounds doesnt cast input values into proper format
- Extracted validation functions for end, start, and min / max lat / lon.
- Validate end and start are always of type datetime.  min / max lat / lon were already being cast to float.
- Pylinting.

CLIMATE-353 Bounds doesnt cast input values into proper format

---

examples/esgf_integration_example.py
ocw/data_source/esgf.py
ocw/esgf/constants.py
ocw/esgf/download.py
ocw/esgf/logon.py
ocw/esgf/main.py
ocw/esgf/search.py

CLIMATE-316 Add ESGF Download Script to repository
- Pylint ESGF modules and examples EXCEPT where it would be a breaking change (e.g. invalid method name).

CLIMATE-316 Add ESGF Download Script to repository

---

ocw/dataset_processor.py

CLIMATE-938 Unify format of the time information from a netCDF file.
- Fix time slice method from throwing error when date objects are of different types.
- Minor pylint.

 CLIMATE-938 Unify format of the time information from a netCDF file.

---

ocw/dataset_processor.py

- dataset_processor._are_bounds_contained_by_dataset is applied only to the cases whose boundary type is 'rectangular'.

CLIMATE-954 - Debug dataset_processor.subset

---

examples/simple_model_to_model_bias.py

The local model files are not downloaded to the temp directory in Windows since the "tmp" directory was introduced in CLIMATE 603.  In order to make the downloads work on Windows as well as Linux (and Mac), this pull request uses tempfile.gettempdir()  identify the optimal temp file location for that operating system.
I am new to this project so I have not yet run the test suite, though I have tested locally.

Climate 964

---

RCMES/CORDEX/templates/CORDEX_evaluation_run.yaml.template
RCMES/run_RCMES.py
ocw/utils.py

- When evaluating GCMs and RCMs forced by GCMs, the added option, 'adjust_model_years_for_climatology_calculation', allows users to calculate climatologies ignoring temporal overlap.

CLIMATE-965 - Add an option to compare climatologies between climate models and observations
