apache/climate

easy-ocw/install-ubuntu.sh
- Stderr redirects should now properly use an append so the install log doesn't get clobbered
=> CLIMATE-566 - Fix output redirect log clobbering bugs

ocw/plotter.py
- add draw_barchart function to plotter.py to plot basic (horizontal) barchart
=> CLIMATE-586 - add barchart as a plotter option

ocw/dataset.py, ocw/dataset_processor.py, ocw/tests/test_dataset.py
- update subset function in DSP to subset 2D (lat,lon) arrays
- update Dataset class to allow 2D (lat,lon) arrays
- update associated test in test_dataset.py to allow 2D arrays
=> CLIMATE-623 - Allow propogation of 2D arrays

ocw/evaluation.py, ocw/tests/test_evaluation.py
- Add tests for unary/binary evaluation results output formatting to
ensure that data is nested properly in the results lists.
- Add subregion support for unary metrics.
- Adjust the ordering that subregions are computed during an evaluation
for performance improvements.
=> CLIMATE-637 - Subregion clean up and improvements

ocw/dataset_processor.py
A new module ocw.dataset_processor.mask_missing_data has been added. Any missing data flag is propagated into the all datasets in the input 'dataset_array'.
=> CLIMATE-648 - Propagation of missing data information from each dataset

ocw/dataset_processor.py
Now users can extract seasonally averaged data between month_start and month_end using dataset_processor.temporal_subset module. By default, seasonal average is not calculated (average_each_year=False).
=> CLIMATE-647 - Update dataset_processor.temporal_subset

ocw/dataset_processor.py, ocw/utils.py
The new module get_temporal_overlap finds maximum temporal overlap across the observation and model datasets.
=> CLIMATE-646 Move the routine to detect temporal overlap between datasets from cli_app to utils

ocw/utils.py
utils.calc_subregion_area_mean_and_std is added to calculate area mean and standard deviation values for a given subregions using datasets on common grid points.
=> CLIMATE-651 - ocw.utils.calc_subregion_area_mean_and_std is added

ocw/dataset_processor.py
The current netcdf generator, dataset_processor.write_netcdf does not support multiple datasets and subregion information. A new module 'write_netcdf_multiple_datasets_with_subregions' complements write_netcdf.
=> CLIMATE-653 - ocw.dataset_processor.write_netcdf_multiple_datasets_with_subregions is added

ocw/utils.py
ocw.utils.calc_area_weighted_spatial_average is added to cCalculate area weighted average of the values in OCW dataset. Area based weighting is optional.
=> CLIMATE-652 - ocw.utils.calc_area_weighted_spatial_average is added

ocw/data_source/local.py
- A new file loader load_multiple_files can read netcdf files with common file name patterns.
=> CLIMATE-564 - Managing multiple netcdf files stored on a local machine

examples/knmi_to_cru31_full_bias.py, ocw/evaluation.py, ocw/tests/test_evaluation.py
- now the evaluation results are provided as a list of missing arrays.
- update _run_no_subregion_evaluation and _run_unary_metric_evaluation in evaluation.py
- update test_evaluation
=> CLIMATE-658 - Restructure evaluation results

ocw-cli/cli_app.py
Take out these two lines:
"9 - Change Plot Title [Coming Soon....]"
"10 - Save the processed data [Coming Soon....]"
=> take out two coming soon items from CLI processing page

ocw-cli/cli_app.py
Need to hide some parameter in CLI to not show up and used not be able to select them.
=> hide some parameter in parameter page

ocw/dataset.py
- without this fix, ocw.dataset.spatial_resolution cannot handle two dimensional latitudes and longitudes
- for curvilinear latitudes and longitudes, the output of ocw.dataset.spatial_resolution is approximate.
- suggested changes in CLIMATE-667 are removed
=> CLIMATE-668 - ocw.dataset_spatial_resolution needs to be fixed

ocw/dataset_processor.py
- ocw.dataset_processsor.subset now handles target_datasets on curvilinear grids where target_datasets.lats and target_datasets.lons are two dimensional variables
=> CLIMATE-671 - Inappropriate spatial subset for datasets on curvilinear grids

ocw/dataset.py, ocw/dataset_processor.py
- ocw.dataset._validate_inputs considers datasets on curvilinear grids
=> CLIMATE-672 - Update the input validation function for OCW datasets

ocw/dataset_processor.py
- ocw.dataset_processor.spatial_regrid is updated to handle two dimensional latitudes and longitudes given as input
=> CLIMATE-674 - Update the spatial_regrid module to handle data on curvilinear grids

examples/statistical_downscaling/MPI_tas_JJA.yaml, examples/statistical_downscaling/run_statistical_downscaling.py
- an example script to statistically downscale the datasets from climate models is added
=> CLIMATE-679 - Statistical downscaling examples

ocw/evaluation.py
- evaluation.convert_evaluation_result and evaluation.convert_unary_evaluation_result have been updated.
- The updated modules properly handle when the metrics calculation result is a single number.
=> Climate-686 - Update the converting functions in ocw.evaluation

ocw/data_source/local.py
- ocw.data_source.local.load_GPM_IMERG_files has been added to read Level 3 IMERG HDF files from the Global Precipitation Measurement mission.
=> Climate-687 - A new loader to read GPM precipitation data with a file list

examples/configuration_file_examples/metrics_and_plots.py, examples/configuration_file_examples/run_RCMES.py, ocw/data_source/local.py
- color map for the bias map is changed
- the model ensemble is calculated only if there are multiple models
=> Climate-688 - Visualization and model ensemble calculation in run_RCMES.py

ocw/data_source/local.py
- ocw.data_source.local.load_WRF_2d_files_RAIN has been added
=> CLIMATE-680 - A new loader to read WRF precipitation data with a filelist

ocw/data_source/local.py
- ocw.data_source.local.load_WRF_2d_files updated
=> CLIMATE-681 - Update the loader to read WRF data 

ocw/data_source/local.py
- A new loader, ocw.data_source.local.load_dataset_from_multiple_netcdf_files, is added
=> CLIMATE-683 - A new loader to read multiple netCDF files with a file list and spatial mask

ocw/data_source/local.py
- ocw.data_source.local.load_NLDAS_forcingA_files is added
=> CLIMATE-692 - A new loader to read NLDAS data with a file list

ocw/dataset_processor.py
- ocw.dataset_processor.temporal_rebin_with_time_index has been added
=> CLIMATE-694 - A new module to rebin a dataset using time index

ocw-cli/cli_app.py
@huikyole please try this PR and if it solved the issue then I can commit to main repo.
Thanks
=> spatial resolution for lat and lon can be different now

examples/configuration_file_examples/metrics_and_plots.py, examples/configuration_file_examples/run_RCMES.py
- run_RCMES.py and metrics_and_plots have been updated.
=> CLIMATE-696 - Examples to evaluate CORDEX-ARCTIC RCMs

ocw/data_source/local.py, ocw/dataset_processor.py
- binned_values is now a numpy.ma array
=> CLIMATE-698 - Handling missing values in ocw.dataset_processor.temporal_rebin_with_time_index

examples/configuration_file_examples/cordex-arctic_cloud_fraction_bias_to_SRB.yaml, examples/configuration_file_examples/cordex-arctic_rlds_bias_to_SRB.yaml, examples/configuration_file_examples/cordex-arctic_rlus_bias_to_SRB.yaml, examples/configuration_file_examples/cordex-arctic_rsds_bias_to_SRB.yaml
- Four configuration (yaml) files have been added.
=> CLIMATE-701 - Examples for evaluation of CORDEX-Arctic RCMs

examples/configuration_file_examples/NARCCAP_paper/Fig10_and_Fig11.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig12_summer.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig12_winter.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig14_and_Fig15.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig16_summer.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig16_winter.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig5_and_Fig6.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig7_summer.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig7_winter.yaml, examples/configuration_file_examples/NARCCAP_paper/Fig8_and_Fig9.yaml, examples/configuration_file_examples/cordex-AF_tasmax_annual_mean_bias_to_cru.yaml
- Ten yaml files have been added in examples/NARCCAP_paper to reproduce the plots in Kim et al.(2013) paper on evaluating NARCCAP RCMs
=> CLIMATE-700 - Complete examples to reproduce a RCMES-based paper

examples/configuration_file_examples/metrics_and_plots.py, examples/configuration_file_examples/run_RCMES.py
- plt.show() has been removed
- The license head has been added
=> CLIMATE-703 - Remove pop-up windows from metrics_and_plots.py

ocw/dataset_processor.py
- ocw.dataset_processor._are_bounds_contained_by_dataset has been updated to make it less sensitive to very small differences in spatial boundary limits
=> CLIMATE-704 - Sensitivity of spatial boundary check in dataset_processor

ocw-vm/Vagrantfile, ocw-vm/init-ocw-vm.sh
- Remove whitespaces from ocw-vm/ related files.
=> Code cleanup

examples/configuration_file_examples/run_RCMES.py, ocw/dataset_processor.py
- ocw.dataset_processor._rcmes_spatial_regrid has been replaced by scipy.interpolate.griddata to properly regrid datasets in curvilinear grid.
=> CLIMATE-714 - Updating the regridding routine

easy-ocw/install-osx.sh, easy-ocw/install-ubuntu.sh
We haven't removed the code discrepancy in the install-ubuntu.sh. This pull request solves it. @lewismc please have a look at this.
=> Resolve CLIMATE-561 : wrapping up the error in install-ubuntu.sh

examples/configuration_file_examples/metrics_and_plots.py
- examples/configuration_file_examples/metrics_and_plots.Taylor_diagram_spatial_pattern_of_multiyear_climatology has been updated.
=> CLIMATE-716 - Dataset object manipulation when plotting a Taylor diagram using a configuration file

ocw/dataset_processor.py
- dataset_processor.temporal_slice has been added
=> CLIMATE-718 - Temporal slice of two-dimensional model output

ocw-ui/frontend/app/scripts/controllers/observationselect.js, ocw-ui/frontend/app/views/selectobservation.html
Addresses the issue CLIMATE-407. Please have a look at it.
=> Resolve CLIMATE-407 Dataset select does not queue empty datasets.

examples/configuration_file_examples/run_RCMES.py
- run_RCMES.py is using ocw.dataset_processor.temporal_slice to slice temporal boundaries in model datasets on curvillinear grids
=> CLIMATE-719 - Subsetting model data on curvillinear grids in the configurationfile runner

ocw-cli/cli_app.py
- ocw-cli/cli_app.py has been updated.
- Spatial subsetting is not applied if the model data uses curvilinear grids.
- Units of all datasets are checked and converted if needed.
- Missing data information is propagated from each dataset to the others.
- CLI uses the recently added metrics class, TemporalMeanBias.
- Climatology plots of an observation and a model are generated.
=> CLIMATE-717 - Debugging CLI

ocw/dataset_processor.py
- ocw.dataset_processor.subset can properly handle datasets on a curvilinear grid by masking grids outside the subdomain.
=> CLIMATE-723 - Update subset module for regional climate model output

ocw/dataset_processor.py
- ocw.dataset_processor.spatial_regrid has been updated.
- check if the new grid points are outside the original domain.
- calculate latitudes and longitudes (float) indices suitable for curvilinear grids
=> CLIMATE-722 - Extrapolation issues in spatial_regrid

ocw/data_source/local.py
- ocw.data_source.local.load_dataset_from_multiple_netcdf_files has been fixed.
=> CLIMATE-724 - Debugging load_dataset_from_multiple_netcdf_files

ocw-ui/frontend/app/scripts/controllers/observationselect.js, ocw-ui/frontend/app/views/selectobservation.html
This patch allows the user to customise the name of the local dataset that is being uploaded in the web-app.
=> CLIMATE-379 - Allows dataset customisation

RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_cloud_fraction_bias_to_SRB.yaml, RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_rlds_bias_to_SRB.yaml, RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_rlus_bias_to_SRB.yaml, RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_rsds_bias_to_SRB.yaml, RCMES/configuration_files/NARCCAP_examples/Fig10_and_Fig11.yaml, RCMES/configuration_files/NARCCAP_examples/Fig12_summer.yaml, RCMES/configuration_files/NARCCAP_examples/Fig12_winter.yaml, RCMES/configuration_files/NARCCAP_examples/Fig14_and_Fig15.yaml, RCMES/configuration_files/NARCCAP_examples/Fig16_summer.yaml, RCMES/configuration_files/NARCCAP_examples/Fig16_winter.yaml, RCMES/configuration_files/NARCCAP_examples/Fig5_and_Fig6.yaml, RCMES/configuration_files/NARCCAP_examples/Fig7_summer.yaml, RCMES/configuration_files/NARCCAP_examples/Fig7_winter.yaml, RCMES/configuration_files/NARCCAP_examples/Fig8_and_Fig9.yaml, RCMES/configuration_files/cordex_AF_prec_subregion_annual_cycle_time_series.yaml, RCMES/statistical_downscaling/MPI_tas_JJA.yaml
=> CLIMATE-726 - Update configuration files

ocw/dataset_processor.py
- ocw.dataset_processor.temperature_unit_conversion has been updated to accept different naming conventions
=> CLIMATE-731 - Update ocw.dataset_processor.temperature_unit_conversion

ocw-ui/frontend/package.json, setup.py
Trivial fix for https://issues.apache.org/jira/browse/CLIMATE-728
=> CLIMATE-728 Address WARN's when building ocwui

RCMES/test/test.py, examples/knmi_to_cru31_full_bias.py, examples/model_ensemble_to_rcmed.py, examples/multi_model_taylor_diagram.py, examples/simple_model_to_model_bias.py, examples/taylor_diagram_example.py, ocw/dataset_processor.py
- efficiency of dataset_processor.temporal_rebin has been significantly improved
- the option for temporal resolution needs to be given as characters.
=> CLIMATE-732 - Update data_processor.temporal_rebin

ocw-ui/frontend/app/index.html, ocw-ui/frontend/app/scripts/app.js, ocw-ui/frontend/app/views/demo.html
- Added a new demo tab.
- The tab includes a demo video of how the web-app works.
- Added a new footer, this prevents the app views from ending abruptly in the web-app.
- The footer contains important links like link to the OCW website and also to the issue tracker.
=> CLIMATE-715 Adding a new demo tab along with the evaluate and result.

RCMES/run_RCMES.py
-  customized names for latitudes and longitudes are allowed.
-  daily or hourly data stored on user's local machine can be used for model evaluation.
=> CLIMATE-733 - Update run_RCMES.py

RCMES/metrics_and_plots.py
- The height of colorbars in RCMES/metrics_and_plots.py has been changed to make the plots look nicer.
=> CLIMATE-734 - Adjust size of the color bars in the map plot of biases

ocw/utils.py
- With this update, it is possible to efficiently handle the netCDF files whose time unit ends with 'Z' character.
=> CLIMATE-735 - Update utils.decode_time_values

ocw/dataset_processor.py
- With this update, ocw.dataset_processor.write_netcdf_multiple_datasets_with_subregions can properly handle datasets on curvilinear grids.
This ticket is also a follow up of CLIMATE-732. There were some errors in ocw.dataset_processor.temporal_rebin.
=> CLIMATE-736 - Update dataset_processor.write_netcdf_multiple_datasets_with_subregions

ocw/dataset_processor.py
-temporal_rebin's keyword, time_unit, is replaced by temporal_resolution.
=> CLIMATE-737 - Debugging dataset_processor.temporal_rebin

RCMES/configuration_files/CORDEX-Africa_examples/Fig10a_cru.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig10b_cru.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig1_2_4a_5.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig3a_summer.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig3a_winter.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig3b_summer.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig3b_winter.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig4d_7d_8ad.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig4f_9bcd.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig7e_8be.yaml, RCMES/configuration_files/CORDEX-Africa_examples/Fig7f_8cf.yaml
- eleven yaml files have been added and tested to evaluate the models participating in CORDEX-Africa using run_RCMES.py.
- Fig10b_trmm.yaml will be added later after addressing CLIMATE-744.
=> CLIMATE-741 - Adding configuration files to evaluate CORDEX-Africa regional climate models

ocw/utils.py
- In ocw.data_source.local.load_file, level_index is fixed as 1 (the 2nd dimension) if the input dataset has four dimensions.
=> CLIMATE-743 - ocw.data_source.local.py cannot properly detect the altitude dimension

ocw-ui/frontend/app/index.html
This PR fixes https://issues.apache.org/jira/browse/CLIMATE-745
=> CLIMATE-745 Report an Issue Link and @copyright year are incorrect in ocw-ui

ocw-ui/backend/run_webservices.py
CLIMATE-740 - Add path handler for img directory to run_webservices.py.
=> CLIMATE-740 - Add path handler for img directory to run_webservices.py.

RCMES/configuration_files/NASA_downscaling_project_Part1/dscale_prmo-eus_rcmed.yaml, RCMES/configuration_files/NASA_downscaling_project_Part1/dscale_prmo-wus_local.yaml, RCMES/configuration_files/NASA_downscaling_project_Part1/dscale_prmo-wus_rcmed.yaml, RCMES/configuration_files/NASA_downscaling_project_Part1/dscale_wus_prec_trmm_vs_nldas.yaml
- A new folder, NASA_downscaling_project_Part1 has been added with four yaml (configuration) files in RCMES/configuration_files.
=> CLIMATE-747 - Adding configuration files as an example of NASA's downscaling project

ocw/dataset_processor.py
- dataset_processor.tempora_rebin has been fixed
- dataset_processor.spatial_regrid has been fixed
=> CLIMATE-748 - Debugging ocw.dataset_processor

MANIFEST.in, setup.cfg, setup.py
This issue addresses https://issues.apache.org/jira/browse/CLIMATE-725
The remainder of the comment can be found over there and I am also going to augment the release procedure to accommodate publishing of OCW to the Cheeseshop.
=> CLIMATE-725 Ensure that OCW 1.1 Test PyPi Works as Expected

ocw-ui/frontend/app/scripts/controllers/observationselect.js
Hi there,
Fixed it.
Let me know if you think anything else could be improved.
=> CLIMATE-750 - Fix a String comparison that should be against a Boolean.

ocw-ui/frontend/app/index.html
Hi there,
Just took this one and added the correct path.
Let me know if you need anything else.
=> CLIMATE-751 - Add the correct path for ui-date.js

RCMES/run_RCMES.py, ocw/dataset_processor.py
- A new optional key, GCM_data, in run_RCMES configuration files
- boundary_check becomes optional in dataset_processor.spatial_regrid
=> CLIMATE-770 - Make boundary checking optional in spatial_regrid

RCMES/cli_app.py
- start_date & end_date inputs are made on the following rows
- datetime objects are used to check temporal sequence
- renamed the metric
- updateed the color map for the climatology plots
- allow multiple spatial regridding options
=> CLIMATE-778 - Cosmetic updates for the cli_app

easy-ocw/ocw-pip-dependencies.txt, ocw/tests/test_utils.py
- Add 'mock' to pip-dependencies
- Fix file path in test_utils.py
=> CLIMATE-774 - Fix failing tests

easy-ocw/conda-install.sh, easy-ocw/install-ubuntu.sh
Can anyone please test this script and post the results.
I have not tested it. I didn't want to mess with my installation.
=> CLIMATE-766 Easy-ocw/install-ubuntu.sh script is broken

docs/source/conf.py, docs/source/config/config_writer.rst, docs/source/index.rst
- Fix configuration_writer import error
- Update table of contents tree
=> CLIMATE-760 - Address documentation warnings

RCMES/configuration_files/ESGF_example/ESGF-Example.yaml, RCMES/run_RCMES.py
integrate ESGF for observation and model data
=> CLIMATE-779 Add capability to run_RCMES.py

RCMES/configuration_files/ESGF_example/ESGF-Example.yaml, RCMES/run_RCMES.py
- Few more keywords have been added to ESGF-Example.yaml
- run_RCMES.py has been updated to handle datasets from ESGF
=> CLIMATE-781 - Fix the ESGF example in run_RCMES.py

easy-ocw/ocw-pip-dependencies.txt, ocw/data_source/esgf.py
This PR addresses https://issues.apache.org/jira/browse/CLIMATE-782
=> CLIMATE-782 Resolve BeautifulSoup warnings in esgf data_source and add myproxyclient to easy-ocw install

RCMES/configuration_files/ESGF_example/ESGF-Example_local.yaml, examples/esgf_integration_example.py
- change name of esgf_integration_examply.py to esgf_integration_example.py
- remove visability of ESGF password on esgf_integration_example.py
- change username prompt to ask for OpenID
- add configuration file for local ESGF example in RCMES
=> CLIMATE-783 Update ESGF examples

examples/esgf_integration_example.py
- the SSL error has been resolved.
=> CLIMATE-790 - SSL errors in the esgf example

RCMES/cli_app.py
Fixed a bug of entering non integer while selecting existing model that causes to crash the CLI.
Also added a new feature that let the user to load a local file from full path beside selecting from existing model files.
=> Upload local model feature

RCMES/cli_app.py
Min and Max time was not showing when user wants to change temporal boundaries.
=> Fix min max time

ocw/data_source/rcmed.py
Fixes https://issues.apache.org/jira/browse/CLIMATE-785
=> CLIMATE-785 - RCMED.py: optimize code

ocw/data_source/rcmed.py, ocw/tests/test_rcmed.py
- Update rcmed.py file
- Fix test_rcmed.py file
Function `test_function_parameter_dataset_lats_monthly` is added to improve test coverage.
Fixes https://issues.apache.org/jira/browse/CLIMATE-786
=> CLIMATE-786 - Update rcmed.py and test_rcmed.py

.coveragerc, .travis.yml
- Use easy-ocw script for build
- Track coverage
- Upload code coverage report to coveralls.io
=> CLIMATE-794 - Update travis.yml

ocw/dataset_processor.py
Fix TypeError in temporal_slice
=> CLIMATE-796 - TypeError in temporal_slice function

ocw/dataset_processor.py
- Fix TypeError in subset function
=> CLIMATE-799 - TypeError in subset function

ocw/dataset_processor.py
- Fix TypeError in dataset processor
=> CLIMATE-800 - TypeError in _rcmes_calc_average_on_new_time_unit

ocw/utils.py
- Fix trivial bug in utils module
=> CLIMATE-804 - normalize_lat_lon_values does not work

ocw/tests/test_dataset.py
Add new tests for dataset module.
=> CLIMATE-801 - Add dataset tests

ocw/tests/test_evaluation.py
Add new tests for evaluation module.
=> CLIMATE-802 - Add evaluation module tests

.coveragerc, ocw/tests/test_plotter.py
- Add tests to verify computations in plotter module
- Update .coveragerc file to ignore image generation code
=> CLIMATE-808 - Add tests for plotter module

ocw-ui/frontend/app/scripts/directives/leafletmap.js, ocw-ui/frontend/app/scripts/directives/previewmap.js
- This PR addresses [CLIMATE-409](https://issues.apache.org/jira/browse/CLIMATE-409?jql=project%20%3D%20CLIMATE%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20%3D%20omkar20895%20ORDER%20BY%20priority%20DESC)
- The map implemented has both english and the regional language at the same time to represent places on the map. 
- For example
=> Implementing a multilingual map in ocw UI

ocw/dataset_processor.py
- Fix PEP8 violations
- Remove unused variables (also a PEP8 violation)
=> CLIMATE-812 - Fix PEP8 violations in dataset processor

ocw/dataset_processor.py
- A very critical typo in ocw.dataset_processor.spatial_regrid has been corrected.
=> CLIMATE-823 - An error from CLIMATE-812

conda_recipes/bottle/bld.bat, conda_recipes/bottle/build.sh, conda_recipes/bottle/meta.yaml, conda_recipes/esgf-pyclient/bld.bat, conda_recipes/esgf-pyclient/build.sh, conda_recipes/esgf-pyclient/meta.yaml, conda_recipes/myproxyclient/bld.bat, conda_recipes/myproxyclient/build.sh, conda_recipes/myproxyclient/meta.yaml, conda_recipes/ocw/bld.bat, conda_recipes/ocw/build.sh, conda_recipes/ocw/meta.yaml, conda_recipes/pydap/bld.bat, conda_recipes/pydap/build.sh, conda_recipes/pydap/meta.yaml, conda_recipes/sphinxcontrib-httpdomain/bld.bat, conda_recipes/sphinxcontrib-httpdomain/build.sh, conda_recipes/sphinxcontrib-httpdomain/meta.yaml
Sorry for forgetting these earlier.
=> CLIMATE-831 - Add ASF headers to conda recipe files

RCMES/run_RCMES.py, ocw/data_source/local.py, ocw/dataset_loader.py, ocw/tests/test_dataset_loader.py
@huikyole please review ASAP. New unit tests pass and I was able to run the examples (note I had to make a slight change to `local.load_multiple_files()`.
=> CLIMATE-839 - Further improvements to DatasetLoader

RCMES/configuration_files/CMIP5_precipitation_evaluation.yaml, RCMES/run_RCMES.py, ocw/dataset_processor.py, ocw/utils.py
- Now users can provide configuration files with the CORDEX domain name to spatially subset datasets using RCMES.
=> CLIMATE-848 - Support CORDEX boundary options in RCMES

test_smoke.py
This PR fixes the Attribute error in test_smoke.py file. The tests are still failing because of broken test cases.
=> CLIMATE-844 - Attribute error in test_smoke.py

ocw/dataset_processor.py
- ocw.dataset_processor.deseasonalize_dataset has been added.
=> CLIMATE-828 - Deseasonalizing functions for OCW datasets

ocw/metrics.py
- calc_histogram_overlap and calc_joint_histogram have been added to ocw.metrics.
=> CLIMATE-849 - Adding joint histogram calculation to the metrics module

ocw/metrics.py
- metrics.wet_spell_analysis has been added
=> CLIMATE-850 - Precipitation intensity and duration analyzer using hourly data

ocw/data_source/local.py, ocw/dataset_processor.py, ocw/tests/test_dataset_processor.py, ocw/tests/test_local.py
- test.local and test.dataset_processor have been updated
=> CLIMATE-855 - Fix test_local and test_dataset_processor

README.md, setup.py
This issue addresses https://issues.apache.org/jira/browse/CLIMATE-859
=> CLIMATE-859 Enable restructured text markdown for Pypi uploads

examples/draw_climatology_map_MISR_AOD.py
- A new example, examples/draw_climatology_map_MISR_AOD.py, has been added.
=> CLIMATE-861 - An example to plot aerosol optical depth climatology from NASA MISR instrument

.travis.yml
This PR addresses https://issues.apache.org/jira/browse/CLIMATE-854
=> CLIMATE-854 Ensure that ocw runs with Python 3.X

RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_cloud_fraction_bias_to_SRB.yaml, RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_rlds_bias_to_SRB.yaml, RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_rlus_bias_to_SRB.yaml, RCMES/configuration_files/CORDEX-Arctic_examples/cordex-arctic_rsds_bias_to_SRB.yaml, RCMES/configuration_files/ESGF_example/ESGF-Example_local.yaml, RCMES/configuration_files/NARCCAP_examples/Fig14_and_Fig15.yaml, RCMES/configuration_files/NARCCAP_examples/Fig16_summer.yaml, RCMES/configuration_files/NARCCAP_examples/Fig16_winter.yaml, RCMES/configuration_files/NASA_downscaling_project_Part1/dscale_prmo-wus_local.yaml, ocw/data_source/local.py, ocw/tests/test_local.py
- ocw.local.load_multiple_files has been updated.
=> CLIMATE-865 - Update dataset_name argument in local.load_multiple_files

RCMES/cli_app.py
- The temporal regridding in cli_app.py has been updated.
=> CLIMATE-867 - CLI error

ocw/dataset_processor.py
- ocw.dataset_processor.subset has been updated with the temporal subset bug fixed
=> CLIMATE-869 - Time range bug in dataset_processor.subset

ocw/dataset_processor.py
- By checking monotonicity of the longitude before regridding, the issue is resolved.
=> CLIMATE-872 - spatial_regrid has a critical issue when longitude=180 exists inside the RCM domain

easy-ocw/install-ubuntu.sh
Addresses https://issues.apache.org/jira/browse/CLIMATE-873
=> CLIMATE-873 easy-ocw install-ubun.sh should use miniconda3

examples/podaac_integration_example.py, ocw/data_source/podaac_datasource.py, ocw/dataset_loader.py, ocw/tests/subset.json, ocw/tests/test_podaac.py
Commit to address https://issues.apache.org/jira/browse/CLIMATE-875
=> CLIMATE-875 Upgrade to Podaacpy 1.4.0

ocw/utils.py
- utils.decode_time_values has been updated
=> CLIMATE-890 - Changing time format when calendar in the netcdf file is 360_day

ocw/tests/test_dap.py, ocw/tests/test_podaac.py
- Skip test if unable to download the dataset
=> CLIMATE-889 - Fix Travis Build

ocw-ui/backend/podaac_helpers.py, ocw-ui/backend/run_webservices.py, ocw-ui/frontend/app/index.html, ocw-ui/frontend/app/scripts/controllers/datasetselect.js, ocw-ui/frontend/app/scripts/controllers/podaacselection.js, ocw-ui/frontend/app/views/selectpodaac.html
- This PR adds PODAAC to OCW GUI.
- This PR will be updated until the community is satisfied with the code addition.
- Right now this is just a template that I have created and I will be adding updates as soon as I hack the code.
- Please don't test this PR until I ask for it, since it is gonna be unstable for a while.
Thanks. :)
=> CLIMATE-877 Adding PODAAC data source to OCW GUI

ocw/data_source/local.py
ocw.data_source.local.load_GPM_IMERG_files has been fixed to maintain the information on missing values.
=> CLIMATE-892 - Fix GPM IMERG data loader

ocw/metrics.py
The errors in ocw.metrics.wet_spell_analysis have been fixed.
=> Climate-893 - Debugging wet_spell_analysis

ocw/utils.py
- ocw.utils.regrid_spatial_mask has been debugged.
=> CLIMATE-894 - Debugging regrid_spatial_mask

ocw/dataset_processor.py, ocw/utils.py
Should fix the errors shown in travis CI for python 3:
https://travis-ci.org/agoodm/climate/jobs/204421839
=> [CLIMATE-897] Make sure shapes of numpy arrays contain only integer values

ocw/data_source/local.py
- ocw.data_source.local.load_WRF_2d_files/load_WRF_2d_files_RAIN have been updated.
=> CLIMATE-898 - Debugging WRF loaders

ocw/dataset_processor.py
-ocw.dataset_processor.temporal_subset has been updated.
=> CLIMATE-900 - Debugging temporal subset

ocw/metrics.py
- ocw.metrics.calc_histogram_overlap has been updated.
=> CLIMATE-901 - Debugging calc_histogram_overlap

ocw/utils.py
- Several bugs in ocw.utils have been fixed.
=> CLIMATE-902 - Debugging regrid_spatial_mask

ocw/data_source/local.py
- ocw.data_source.local.load_GPM_IMERG_files_with_spatial_filter has been added
=> CLIMATE-899 - Update the GPM loader

examples/temperature_trends_over_CONUS.py, ocw/dataset_processor.py, ocw/plotter.py, ocw/tests/test_dataset_processor.py, ocw/utils.py
- debugging in dataset_processor
- A new module (utils.calculate_temporal_trends) to calculate the least square trend and standard error in the input time series.
- A new module (plotter.fill_US_states_with_color) to visualize US NCA regions
=> CLIMATE-903 - Adding a module to calculate the least square trend and standard error

examples/temperature_trends_over_CONUS.py, ocw/data_source/local.py, ocw/dataset_processor.py, ocw/plotter.py, ocw/tests/test_local.py, ocw/utils.py
- example/temperature/trends_over_CONUS.py has been updated
- data_source.local.load_multiple_files has been updated to load the CMIP5 files without file concatenation.
- dataset_processor has been updated.
- plotter has a new module (draw_plot_to_compare_trends) to generate a plot to compare observed trends with simulated ones.
- test_local.py has been updated to reflect the changes in
- utils.calculate_temporal_trend_of_time_series has been debugged.
- utils.calculate_ensemble_temporal_trends has been updated.
=> CLIMATE-905 - Box whisker plot to evaluate simulated trends

ocw/dataset_processor.py, ocw/utils.py
This should fix the build errors for python 3.
=> [CLIMATE 910] Throw an exception for inconsistent temporal reshaping / rebinning operatations

examples/GPM_WRF24_JPDF_comparison.py, ocw/data_source/local.py, ocw/metrics.py, ocw/plotter.py
- A new example, GPM_WRF24_JPDF_comparison, has been added.
- Joint PDF metric has been debugged.
- A new plotting module, draw_precipitation_JPDF, has been added.
=> CLIMATE-909 - An example script to evaluate joint PDF of precipitation intensity and duration

ocw/dataset_processor.py
- By applying int() to central_index, the warning has been addressed.
=> CLIMATE-907 - Fix VisibleDeprecationWarning's in ocw.tests.test_dataset_processor.TestTemporalSubset

.gitignore, examples/podaac_integration_example.py, examples/simple_model_tstd.py, ocw/data_source/local.py, ocw/data_source/podaac_datasource.py, ocw/dataset_loader.py, ocw/tests/subset.json, ocw/tests/test_podaac.py
Hi folks, this is the attempt to upgrade to Podaacpy 1.9.0, @Omkar20895 can you try this out? You can also try the example and tests which should give you a good idea of how stable this is.
I've [logged an issue](https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=53&t=579) over at the PO.DAAC Forum regarding dataset subsetting, so I will update this depending on the outcome of that.
=> CLIMATE-885 Upgrade to Podaacpy 1.9.0

RCMES/cli_app.py
All of the options shown in the run screen work after applying this fix.
=> CLIMATE-913 - Bugs in CLI

ocw/dataset_processor.py, ocw/tests/test_dataset_processor.py
- map_coordinates has been replaced with scipy.interpolate.griddata.
=> CLIMATE-914 - Update dataset_processor.spatial_regrid module

RCMES/configuration_files/NARCCAP_examples/Fig14_and_Fig15.yaml, RCMES/configuration_files/NARCCAP_examples/Fig16_summer.yaml, RCMES/configuration_files/NARCCAP_examples/Fig16_winter.yaml
- Fig14_and_Fig15.yaml, Fig16_summer.yaml, and Fig16_winter.yaml have been updated.
=> CLIMATE-915 - Updates for the NARCCAP example configuration files

ocw/utils.py
- ocw.utils.decode_time_value has been fixed
=> CLIMATE-916 - Checking netcdf files' file format

ocw/data_source/local.py
- LAT_NAMES and LON_NAMES in ocw.data_source.local have been revised to prevent loading wrong variables for longitudes and latitudes when using OCW loaders
=> CLIMATE-918 - Revise LAT_NAMES and LON_NAMES

examples/esgf_integration_example.py, examples/podaac_integration_example.py, examples/simple_model_to_model_bias.py, examples/taylor_diagram_example.py, examples/time_series_with_regions.py, mccsearch/code/mccSearch.py, ocw/data_source/esgf.py, ocw/esgf/download.py
This issue addresses https://issues.apache.org/jira/browse/CLIMATE-920
=> CLIMATE-920 Make examples Python 3 compatible

mccsearch/code/mccSearch.py
use a set to track visiting state. also some minor updates.
=> optimizing traversing

RCMES/CORDEX/templates/CORDEX.yaml.template, RCMES/metrics_and_plots.py, RCMES/run_RCMES.py, ocw/data_source/local.py, ocw/utils.py
@huikyole The final script will come in just a bit (CLIMATE-926). However you can test these changes yourself by rendering the config file. Try running this script in the `climate/RCMES/CORDEX` directory. (You'll need jinja2, `conda install jinja2`):
```python
import jinja2
from metadata_extractor import CORDEXMetadataExtractor, obs4MIPSMetadataExtractor
workdir = '/home/goodman/data_processing/CORDEX/analysis' # CHANGEME
obs_extractor = obs4MIPSMetadataExtractor('/proj3/data/obs4mips')
models_extractor = CORDEXMetadataExtractor('/proj3/data/CORDEX/NAM-44/*')
groups = obs_extractor.group(models_extractor, 'variable')
obs_info, models_info = groups[0]
env =  jinja2.Environment(loader=jinja2.FileSystemLoader('./templates'), trim_blocks=True, lstrip_blocks=True)
t = …
```
=> CLIMATE-925 - CORDEX Config File Template

RCMES/CORDEX/cordex.py, RCMES/CORDEX/metadata_extractor.py, RCMES/CORDEX/templates/CORDEX.yaml.template, RCMES/metrics_and_plots.py, RCMES/run_RCMES.py, ocw/plotter.py, ocw/tests/test_plotter.py
Finally done and working at an acceptable level. This required several bug fixes and feature adjustments, including:
1) Setting default values for subplot_array (gridshape) and start and end times (via max temporal overlap)
2) Fixing minor bug in parsing CORDEX boundary info
3) Prefer "portrait" aspect ratios to "landscape" for default subplot arrays (eg, (3, 2) instead of (2, 3) for 6 plots).
=> CLIMATE-927 - RCMES script for running multiple evaluations

RCMES/run_RCMES.py
- RCMES/run_RCMES.py has been fixed
=> CLIMATE-932 - A whitespace error in running the CORDEX script

examples/time_series_with_regions.py
CLIMATE-934 
- Fixed error with out of date Bounds constructor. 
- Addressed error with matplotlib and epoch date.
- Added Apache license.
- Minor Pylint.
=> CLIMATE-934 Fixed error with out of date Bounds constructor.  

examples/GPM_WRF24_JPDF_comparison.py, examples/draw_climatology_map_MISR_AOD.py, examples/esgf_integration_example.py, examples/knmi_to_cru31_full_bias.py, examples/model_ensemble_to_rcmed.py, examples/multi_model_evaluation.py, examples/multi_model_taylor_diagram.py, examples/podaac_integration_example.py, examples/simple_model_to_model_bias.py, examples/simple_model_tstd.py, examples/subregions_portrait_diagram.py, examples/subregions_rectangular_boundaries.py, examples/subset_TRMM_data_for_NCA_regions.py, examples/taylor_diagram_example.py, examples/temperature_trends_over_CONUS.py, examples/time_series_with_regions.py
Climate 465
- Added class level documentation.
- Added Apache license.
=> Climate 465

examples/GPM_WRF24_JPDF_comparison.py, examples/draw_climatology_map_MISR_AOD.py, examples/esgf_integration_example.py, examples/knmi_to_cru31_full_bias.py, examples/model_ensemble_to_rcmed.py, examples/multi_model_evaluation.py, examples/multi_model_taylor_diagram.py, examples/podaac_integration_example.py, examples/simple_model_to_model_bias.py, examples/simple_model_tstd.py, examples/subregions_portrait_diagram.py, examples/subregions_rectangular_boundaries.py, examples/subset_TRMM_data_for_NCA_regions.py, examples/taylor_diagram_example.py, examples/temperature_trends_over_CONUS.py, examples/time_series_with_regions.py, ocw/dataset_processor.py
CLIMATE-797 
- Fix Attribute error when dataset does not have mask attribute.
=> CLIMATE-797 - Fix Attribute error when dataset does not have mask attribute.

examples/GPM_WRF24_JPDF_comparison.py, examples/draw_climatology_map_MISR_AOD.py, examples/esgf_integration_example.py, examples/knmi_to_cru31_full_bias.py, examples/model_ensemble_to_rcmed.py, examples/multi_model_evaluation.py, examples/multi_model_taylor_diagram.py, examples/podaac_integration_example.py, examples/simple_model_to_model_bias.py, examples/simple_model_tstd.py, examples/subregions_portrait_diagram.py, examples/subregions_rectangular_boundaries.py, examples/subset_TRMM_data_for_NCA_regions.py, examples/taylor_diagram_example.py, examples/temperature_trends_over_CONUS.py, examples/time_series_with_regions.py, ocw/dataset_processor.py
CLIMATE-936
- Added instructions on where files for example could be downloaded.
- Changed references to filename to match filename of downloaded file.
=> CLIMATE-936

docs/source/index.rst, docs/source/ocw/statistical_downscaling.rst, ocw/statistical_downscaling.py
CLIMATE-626 Update doc strings in Downscaling class
- Added missing docstrings.
- Updated documentation templates.
- Pylinted Downscaling class.
=> CLIMATE-626 Update doc strings in Downscaling class

ocw-ui/frontend/app/scripts/services/evaluationsettings.js
CLIMATE-366 Add full temporal rebin option to UI
- Added full rebin option.
- Renamed 'yearly' option to annual to be consistent with rebin methods.
=> CLIMATE-366 Add full temporal rebin option to UI

ocw/plotter.py
CLIMATE-625 Update draw_histogram and draw_marker_on_map documentation
- Update documentation for histogram and marker methods to detail input and output types.
=> CLIMATE-625 Update draw_histogram and draw_marker_on_map documentation

docs/source/conf.py, ocw-ui/backend/rcmed_helpers.py, ocw/dataset.py, ocw/dataset_loader.py, ocw/utils.py
CLIMATE-917 Bocumentation build error with Python3
- Cleared all WARNING when running make html.
- Added Sphinx extension for bottle.
=> CLIMATE-917 Bocumentation build error with Python3

RCMES/CORDEX/cordex.py
=> CLIMATE-946 - CORDEX script does not necessarily use correct interpreter when calling RCMES

RCMES/CORDEX/cordex.py
The goal of this PR is to facilitate building a RCMES docker image.
- The variable 'errored' is defined outside a for loop.
- domain, workdir, obs_dir, and models_dir can be sys.argv
=> CLIMATE-947 - Updates in cordex.py

examples/model_ensemble_to_rcmed.py
- Keyed start date off of dataset post re-bin rather than hard code to ensure data set and bounds are consistent.
=> CLIMATE-826 ValueError in model_ensemble_to_rcmed.py

ocw/data_source/rcmed.py
CLIMATE-744 Cannot load TRMM data from RCMED
- Break single,  multi year requests to RCMED into several smaller requests to avoid single, ultra large, but partial, result sets.
=> CLIMATE-744 Cannot load TRMM data from RCMED

ocw/data_source/podaac_datasource.py, ocw/tests/test_podaac.py
This PR addresses https://issues.apache.org/jira/browse/CLIMATE-948
=> CLIMATE-948 cleanup podaac_datasource to accomodate Podaacpy 2.1.0

ocw/dataset_processor.py
- write_netcdf and write_netcdf_multiple_datasets_with_subregions have been updated
- now the time dimension is unlimited
- x and y are names for the dimensions for longitudinal and latitudinal coordinates
=> CLIMATE-952 - Update ocw.data_processor.write_netcdf to compatible wUpdate ocw.data_processor.write_netcdf to compatible with xarray

ocw/dataset_processor.py
- the bug that used netCDF4.netcdftime attribute has been fixed
=> CLIMATE-955 - Bugs in dataset_processor.temporal_slice

RCMES/statistical_downscaling/run_statistical_downscaling.py
- Some of the changes made by PR #444 have been reverted to make the codes work.
=> CLIMATE-956 - Revert the changes in run_statistical_downscaling.py

deps_py2.txt
=> Add lxml for travis fix

ocw/metrics.py, ocw/tests/test_metrics.py
Fixes issue https://issues.apache.org/jira/browse/CLIMATE-957
=> [CLIMATE - 957] Include Absolute Biasing under Metrics

ocw/data_source/local.py
local.load_file has been updated to mask NaN values
=> CLIMATE-962 Handling of NAN values while loading datasets

RCMES/CORDEX/cordex.py
=> CLIMATE-963 Enabling Python command line arguments for cordex.py

docs/source/ocw/overview.rst
I'm new to the project and did my best to maintain consistent, correct use of terminology, but it's plenty likely I messed up somewhere. Happy to tweak.
=> Copyedit overview.rst

RCMES/CORDEX/CORDEX.ipynb
- CORDEX.ipynb, a Jupyter notebook version of cordex.py, has been added in RCMES/CORDEX.
=> CLIMATE-966 - Jupyter Notebook to run cordex.py on AWS

RCMES/statistical_downscaling/run_statistical_downscaling.py, dmitri_example.ipynb
Print statement update from Python 2.x to 3.x syntax
=> Climate 968
